name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x] # Use a valid Node.js version
    env:
      NEXT_PUBLIC_BASE_API: ${{ secrets.NEXT_PUBLIC_BASE_API }}    
      NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}    
      NEXT_ACCESS_KEY: ${{ secrets.NEXT_ACCESS_KEY }}
      NEXT_POST_ACCESS_KEY: ${{ secrets.NEXT_POST_ACCESS_KEY }}
       
    steps:
    - name: Debug User and Permissions
      run: |
        echo "Running as user: $(whoami)"
        ls -ld /home/shuvobaroi_portfolio/actions-runner/_work/shuvobaroi-portfolio
        ls -l /home/shuvobaroi_portfolio/actions-runner/_work/shuvobaroi-portfolio

    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install Dependencies
      run: pnpm i

    - name: Debug Secrets
      run: |
        echo "NEXT_PUBLIC_BASE_API=${{ secrets.NEXT_PUBLIC_BASE_API }}"
        echo "NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }}"
        echo "NEXT_ACCESS_KEY=${{ secrets.NEXT_ACCESS_KEY }}"
        echo "NEXT_POST_ACCESS_KEY=${{ secrets.NEXT_POST_ACCESS_KEY }}"
      shell: bash

    - name: Build
      run: pnpm build
      env:
        NEXT_PUBLIC_BASE_API: ${{ secrets.NEXT_PUBLIC_BASE_API }}
        NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}
        NEXT_ACCESS_KEY: ${{ secrets.NEXT_ACCESS_KEY }}
        NEXT_POST_ACCESS_KEY: ${{ secrets.NEXT_POST_ACCESS_KEY }}

    - name: List PM2 Processes
      run: pm2 list

    - name: Restart Application
      run: pm2 restart 0
      working-directory: /home/shuvobaroi_portfolio/actions-runner/_work/shuvobaroi-portfolio/shuvobaroi-portfolio
