name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      NEXT_PUBLIC_BASE_API: ${{ secrets.NEXT_PUBLIC_BASE_API }}    
      NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}    
      NEXT_ACCESS_KEY: ${{ secrets.NEXT_ACCESS_KEY }} 
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install pnpm
      run: npm install -g pnpm

    - run: pnpm i

    - run: pnpm build
    - name: Change Directory
      run: cd /home/shuvobaroi_portfolio/actions-runner/_work/shuvobaroi-portfolio/shuvobaroi-portfolio
    - run: pm2 restart 0 
    
    # - run: npm test
